version: "3"

services:
  nginx-service:
    image: nginx
    ports:
    - 11111:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/srv/www
    depends_on:
      - php-service

  php-service:
    build: ./dockerfiles/php-fpm
    volumes:
      - ../:/srv/www

  mysql-service:
    image: mysql:5.7
    ports:
    - 35011:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "developer"
      MYSQL_PASSWORD: "developer"
      MYSQL_DATABASE: "test_project"
    networks:
      default:
        aliases:
          - testproject.mysql.host